# Generated by Django 5.2.12 on 2026-06-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='python manage.py migrate', upload_to='about/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
